package net.jacobpeterson.spigot.player.data;

import net.jacobpeterson.spigot.PvPPlugin;
import net.jacobpeterson.spigot.player.PvPPlayer;
import org.bukkit.scheduler.BukkitRunnable;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PlayerBukkitDataRemoveRunnable extends BukkitRunnable {

    private final Logger LOGGER;

    private PvPPlayer pvpPlayer;
    private PlayerDataManager playerDataManager;
    private Runnable completionRunnable;

    /**
     * Instantiates a new PlayerBukkitDataRemoveRunnable which will remove the data file generated by bukkit:
     * <world>/playerdata/<UUID>.dat for every world.
     *
     * @param pvpPlayer          the pvp player
     * @param playerDataManager  the player data manager
     * @param completionRunnable the completion runnable
     */
    public PlayerBukkitDataRemoveRunnable(PvPPlayer pvpPlayer, PlayerDataManager playerDataManager,
                                          Runnable completionRunnable) {
        LOGGER = PvPPlugin.getPluginLogger();
        this.pvpPlayer = pvpPlayer;
        this.playerDataManager = playerDataManager;
        this.completionRunnable = completionRunnable;
    }

    @Override
    public void run() {
        try {
            playerDataManager.deleteBukkitPlayerDataFile(pvpPlayer);
        } catch (IOException exception) {
            LOGGER.log(Level.SEVERE, "Could not run bukkit player data deletion!", exception);
        }

        if (completionRunnable != null) {
            completionRunnable.run();
        }
    }
}
