package net.jacobpeterson.spigot.player.data;

import net.jacobpeterson.spigot.PvPPlugin;
import net.jacobpeterson.spigot.player.PvPPlayer;
import net.jacobpeterson.spigot.util.ExceptionTracker;
import net.jacobpeterson.spigot.util.InstanceRunnable;
import org.bukkit.scheduler.BukkitRunnable;

import java.io.IOException;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.logging.Logger;

public class PlayerBukkitDataRemoveRunnable extends BukkitRunnable implements ExceptionTracker {

    private final Logger LOGGER;

    private PvPPlayer pvpPlayer;
    private PlayerDataManager playerDataManager;
    private InstanceRunnable<PlayerBukkitDataRemoveRunnable> instanceRunnable;
    private ArrayList<AbstractMap.SimpleEntry<String, Exception>> exceptions;

    /**
     * Instantiates a new PlayerBukkitDataRemoveRunnable which will remove the data file generated by bukkit:
     * <world>/playerdata/<UUID>.dat for every world.
     *
     * @param pvpPlayer         the pvp player
     * @param playerDataManager the player data manager
     * @param instanceRunnable  the instance runnable
     */
    public PlayerBukkitDataRemoveRunnable(PvPPlayer pvpPlayer, PlayerDataManager playerDataManager,
                                          InstanceRunnable<PlayerBukkitDataRemoveRunnable> instanceRunnable) {
        LOGGER = PvPPlugin.getPluginLogger();
        this.pvpPlayer = pvpPlayer;
        this.playerDataManager = playerDataManager;
        this.instanceRunnable = instanceRunnable;
        this.exceptions = new ArrayList<>();
    }

    @Override
    public void run() {
        try {
            playerDataManager.deleteBukkitPlayerDataFile(pvpPlayer);
        } catch (IOException exception) {
            exceptions.add(new AbstractMap.SimpleEntry<>("Error delete bukkit player data for: "
                    + pvpPlayer.getPlayer().getName(), exception));
        }

        if (instanceRunnable != null) {
            instanceRunnable.run(this);
        }
    }

    @Override
    public boolean didExceptionOccur() {
        return exceptions.size() > 0;
    }

    @Override
    public ArrayList<AbstractMap.SimpleEntry<String, Exception>> getExceptions() {
        return exceptions;
    }
}
